[package]
name = "pepeeltoro41/jecs-vide"
version = "1.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "node_modules",
    "src/index.d.ts",
    "package.json",
    "jecs.luau",
    "vide.luau",
]

[dependencies]
jecs = "ukendio/jecs@^0.9.0"
vide = "centau/vide@^0.4.0"
jecs-utils = "pepeeltoro41/jecs-utils@^1.4.0"
