[package]
name = "pepeeltoro41/jecs-gizmo"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["node_modules", "src/index.d.ts", "package.json", "jecs.luau"]

[dependencies]
jecs = "ukendio/jecs@0.10.0"
